#!/usr/bin/env python3
"""review_queue.csv (human) + image_annotations.csv (model) -> image_annotations.confirmed.csv

Ownership boundary, deliberately strict:

  data/annotations/image_annotations.csv   MODEL owns. Regenerated by the vision
                                           pass. Never edit by hand.
  data/annotations/review_queue.csv        HUMAN owns. Never written by any
                                           script, including this one.
  data/annotations/image_annotations.confirmed.csv
                                           The join. Regenerated freely; a
                                           confirmed row is pinned, so a later
                                           vision pass cannot overwrite it.

Both the model's proposal and the human's verdict are kept side by side, so the
audit trail survives (Agents.md sec. 8: explicit and inferred stay separate).

verdict values:
  ok      accept the model's reading as-is
  fix     use the fix_* columns instead
  unsure  needs another look; stays unconfirmed and is reported
  <blank> not reviewed yet
"""
import csv
import os
import sys
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
ANN = os.path.join(HERE, "..", "data", "annotations", "image_annotations.csv")
REV = os.path.join(HERE, "..", "data", "annotations", "review_queue.csv")
OUT = os.path.join(HERE, "..", "data", "annotations", "image_annotations.confirmed.csv")

COLS = ["tweet_id", "date", "image_type", "pages_shown", "transcribed_text",
        "chapters", "stage_raw", "confidence", "notes",
        "status", "source_of_truth", "verdict", "reviewer_note",
        "model_image_type", "model_pages_shown", "model_transcribed_text",
        "confirmed_at"]


def read(path, **kw):
    if not os.path.exists(path):
        sys.exit("missing: %s" % path)
    with open(path, encoding=kw.get("encoding", "utf-8-sig")) as fh:
        return list(csv.DictReader(fh))


def main():
    ann = {r["tweet_id"]: r for r in read(ANN)}
    rev = {r["tweet_id"]: r for r in read(REV)}

    unknown = set(rev) - set(ann)
    if unknown:
        print("WARNING: %d review rows have no matching annotation: %s"
              % (len(unknown), sorted(unknown)[:5]))

    now = datetime.now(timezone.utc).isoformat()
    rows, counts = [], {"ok": 0, "fix": 0, "unsure": 0, "unreviewed": 0}
    for tid, a in sorted(ann.items(), key=lambda kv: kv[1]["date"]):
        r = rev.get(tid, {})
        verdict = (r.get("verdict") or "").strip().lower()

        out = {
            "tweet_id": tid, "date": a["date"],
            "image_type": a["image_type"], "pages_shown": a["pages_shown"],
            "transcribed_text": a["transcribed_text"],
            "chapters": a["chapters"], "stage_raw": a["stage_raw"],
            "confidence": a["confidence"], "notes": a["notes"],
            "verdict": verdict, "reviewer_note": (r.get("reviewer_note") or "").strip(),
            "model_image_type": a["image_type"], "model_pages_shown": a["pages_shown"],
            "model_transcribed_text": a["transcribed_text"],
            "confirmed_at": "",
        }

        if verdict == "fix":
            for field, col in (("image_type", "fix_image_type"),
                               ("pages_shown", "fix_pages"),
                               ("transcribed_text", "fix_text")):
                val = (r.get(col) or "").strip()
                if val:
                    out[field] = val
            out.update(status="confirmed", source_of_truth="human_corrected",
                       confidence="high", confirmed_at=now)
            counts["fix"] += 1
        elif verdict == "ok":
            out.update(status="confirmed", source_of_truth="human_confirmed",
                       confidence="high", confirmed_at=now)
            counts["ok"] += 1
        elif verdict == "unsure":
            out.update(status="needs_review", source_of_truth="model_proposed")
            counts["unsure"] += 1
        else:
            out.update(status="proposed", source_of_truth="model_proposed")
            counts["unreviewed"] += 1
        rows.append(out)

    with open(OUT, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=COLS)
        w.writeheader()
        w.writerows(rows)

    total = len(rows)
    done = counts["ok"] + counts["fix"]
    print("wrote %s" % os.path.basename(OUT))
    print("  confirmed ok   %4d" % counts["ok"])
    print("  corrected      %4d" % counts["fix"])
    print("  needs review   %4d" % counts["unsure"])
    print("  unreviewed     %4d" % counts["unreviewed"])
    print("  --------------------")
    print("  %d/%d confirmed (%.0f%%)" % (done, total, 100.0 * done / total))
    if counts["fix"]:
        print("\ncorrections applied:")
        for r in rows:
            if r["verdict"] == "fix":
                print("  %s %s  %s/%s -> %s/%s  %s"
                      % (r["date"], r["tweet_id"][-6:], r["model_image_type"],
                         r["model_pages_shown"] or r["model_transcribed_text"][:18],
                         r["image_type"], r["pages_shown"] or r["transcribed_text"][:18],
                         r["reviewer_note"]))


if __name__ == "__main__":
    main()
